pipeline {
    // 스테이지 별로 다른 거
    agent any

    triggers {
        pollSCM('*/3 * * * *')
    }

    environment {
      AWS_ACCESS_KEY_ID = credentials('awsAccessKeyId')
      AWS_SECRET_ACCESS_KEY = credentials('awsSecretAccessKey')
      AWS_DEFAULT_REGION = 'ap-northeast-2'
      EMAIL_ADDRESS = ''
      HOME = '.' // Avoid npm root owned
    }

    stages {
        // 레포지토리를 다운로드 받음
        stage('Prepare') {
            agent any
            
            steps {
                echo 'Clonning Repository'

                git url: 'https://github.com/hoonn9/first-jenkins.git',
                    branch: 'master',
                    credentialsId: 'gittest'
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    echo 'Successfully Cloned Repository'
                }

                // 항상 실행
                always {
                  echo "i tried..."
                }

                cleanup {
                  echo "after all other post condition"
                }
            }
        }

        
        // stage('Only for production') {
        //   // 조건 줄때 
        //   // 브랜치가 production 이고 APP_ENV 값이 prod 일때 DEPLOY_TO 로
        //   when {
        //     branch 'production'
        //     environment name: 'APP_ENV', value: 'prod'
        //     anyOf {
        //       environment name: 'DEPLOY_TO', value: 'production'
        //       environment name: 'DEPLOY_TO', value: 'staging'
        //     }
        //   }
        // }
        
        // aws s3 에 파일을 올림
        stage('Deploy Frontend') {
          steps {
            echo 'Deploying Frontend'
            // 프론트엔드 디렉토리의 정적파일들을 S3 에 올림, 이 전에 반드시 EC2 instance profile 을 등록해야함.
            dir ('./website'){
                sh '''
                aws s3 sync ./ s3://first-jenkins-hoon
                '''
            }
          }

          post {
              // If Maven was able to run the tests, even if some of the test
              // failed, record the test results and archive the jar file.
              success {
                  echo 'Successfully Cloned Repository'

                  mail  to: "${env.EMAIL_ADDRESS}",
                        subject: "Deploy Frontend Success",
                        body: "Successfully deployed frontend!"

              }

              failure {
                  echo 'I failed :('

                  mail  to: "${env.EMAIL_ADDRESS}",
                        subject: "Failed Pipelinee",
                        body: "Something is wrong with deploy frontend"
              }
          }
        }
        
        stage('Lint Backend') {
            // Docker plugin and Docker Pipeline 두개를 깔아야 사용가능!
            // production 에서는 ecr repository => aws키가 접근 가능해야함
            agent {
              docker {
                image 'node:latest'
              }
            }
            
            steps {
              dir ('./server'){
                  sh '''
                  npm install&&
                  npm run lint
                  '''
              }
            }
        }
        
        stage('Test Backend') {
          agent {
            docker {
              image 'node:latest'
            }
          }
          steps {
            echo 'Test Backend'

            dir ('./server'){
                sh '''
                npm install
                npm run test
                '''
            }
          }
        }
        
        stage('Bulid Backend') {
          agent any
          steps {
            echo 'Build Backend'

            // build arg 멀티 배포 환경, 
            // env 에 따라 jenkinsfile을 나누는 것보다 application 단계에서 해결하는 게 더 좋다.
            dir ('./server'){
                sh """
                docker build . -t server --build-arg env=${PROD}
                """
            }
          }

          // 빌드 하다 실패 시 파이프라인 종료
          post {
            failure {
              error 'This pipeline stops here...'
            }
          }
        }
        
        // ecs 업데이트 또는 쿠버네티스 업데이트
        stage('Deploy Backend') {
          agent any

          steps {
            echo 'Build Backend'

            dir ('./server'){
                // docker rm -f $(docker ps -aq)
                sh '''
                docker run -p 80:80 -d server
                '''
            }
          }

          post {
            success {
              mail  to: "${env.EMAIL_ADDRESS}",
                    subject: "Deploy Success",
                    body: "Successfully deployed!"
            }
          }
        }
    }
}
